### ISSUE TITLE
Just download in Github but unfortunately not working on my server

### ISSUE THREAD

**Issue by Scaramask** [mdobydullah/vue.js-routing-using-cdn#1]
Hello Friend 

I'm used to installing my view applications from the command line. I deed try to run  your application from vscode with life server but the router is it not working as expected, also tried with a real server but unfortunately without succes.
Please could you help me...

Christopher

**Comment by mdobydullah** [comment]
Hi @Scaramask,

I've checked. The article was written using Vue 2. Now, Vue 3.2.37 is running. Version issue is the problem.

I've just published a new article. Please follow this one: [Vue.js 3 Routing From Scratch Using CDN Without CLI](https://shouts.dev/articles/vuejs-3-routing-from-scratch-using-cdn-without-cli)

Also, you can check this GitHub repo: [https://github.com/shoutsdev/vuejs3-routing-using-cdn](https://github.com/shoutsdev/vuejs3-routing-using-cdn)

Thanks.

**Comment by Scaramask** [comment]
Hello 😉

Thank you so much my friend, now everything work perfectly for me.

I am 65 years old geek studying Vue js and you help a lot…

Have a very good day 👍🏽

**Comment by mdobydullah** [comment]
Hi @Scaramask,

OMG... You're 65!!! It has inspired me a lot.

Best wishes to you, my friend. 🙂

**Comment by mdobydullah** [comment]
> Hello 😉 Thank you so much my friend, now everything work perfectly for me. I am 65 years old geek studying Vue js and you help a lot… Have a very good day 👍🏽

OMG!! You are 65..!!!

It inspired me a lot. Best wishes to you, my friend. 💖✌
